local wezterm = require("wezterm")

return {
	color_scheme = "Everblush",
	freetype_load_target = 'Light',
	freetype_render_target = 'HorizontalLcd',
	font_size = 12.6,
	font = wezterm.font_with_fallback({
		-- {
		-- 	family = "JetBrainsMono Nerd Font Mono",
		-- 	weight = "Medium",
		-- 	italic = false,
		-- 	harfbuzz_features = {
		-- 		"zero",
		-- 		"ss01",
		-- 		"ss02",
		-- 		"ss03",
		-- 		"ss04",
		-- 		"ss05",
		-- 		"ss07",
		-- 		"ss08",
		-- 		"cv30",
		-- 		"cv31",
		-- 		"cv25",
		-- 		"cv26",
		-- 		"cv32",
		-- 		"onum",
		-- 	},
		-- },
		{
			family = "Fira Code",
			weight = "DemiBold",
			italic = false,
			harfbuzz_features = {
				"zero",
				"ss01",
				"ss02",
				"ss03",
				"ss04",
				"ss05",
				"ss07",
				"ss08",
				"cv30",
				"cv31",
				"cv25",
				"cv26",
				"cv32",
				"onum",
			},
		}
	}),
	window_background_opacity = 0.9,
	window_frame = {
		font = wezterm.font({ family = "Roboto", weight = "Medium" }),
		font_size = 12.8,
	},
	window_padding = {
		left = 2,
		right = 2,
		top = 0,
		bottom = 0,
	},
	use_dead_keys = true,
	audible_bell = "Disabled",
	leader = { key = "b", mods = "CTRL", timeout_milliseconds = 1000 },
	keys = {
		{ key = "C", mods = "CTRL", action = wezterm.action.CopyTo("Clipboard") },
		{ key = "-", mods = "CTRL", action = wezterm.action.DecreaseFontSize },
		{ key = "=", mods = "CTRL", action = wezterm.action.IncreaseFontSize },
		{ key = "Backspace", mods = "CTRL|SHIFT", action = wezterm.action.ResetFontSize },
		{
			key = "|",
			mods = "LEADER|SHIFT",
			action = wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }),
		},
		{
			key = "-",
			mods = "LEADER",
			action = wezterm.action.SplitVertical({ domain = "CurrentPaneDomain" }),
		},
	},
}
