gui:
  authorColors:
    '*': '#b4befe'
  theme:
    cherryPickedCommitBgColor:
      - '#45475a'
    activeBorderColor:
      - '#89b4fa'
      - bold
    unstagedChangesColor:
      - '#f38ba8'
    selectedLineBgColor:
      - '#313244'
    searchingActiveBorderColor:
      - '#f9e2af'
      - "bold"
    optionsTextColor:
      - '#89b4fa'
    inactiveBorderColor:
      - '#a6adc8'
    defaultFgColor:
      - '#cdd6f4'
    cherryPickedCommitFgColor:
      - '#89b4fa'
  nerdFontsVersion: "3"
  border: "double"
git:
  paging:
    colorArg: always
    pager: "delta --dark --paging=never"
    useConfig: false

os:
  editPreset: "nvim"
